apiVersion: v1
kind: Service
metadata:
  labels:
    app: resume-deploy
  name: resume-deploy-cluster-ip
  namespace: resume-ns
spec:
  ports:
  - port: 9080
    protocol: TCP
    targetPort: 80
  selector:
    app: resume-deploy
  type: ClusterIP
status:
  loadBalancer: {}
